# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  # push:
  #   branches: ['main']

  # Ручной запуск
  workflow_dispatch:
    # Добавляет чекбокс для использования артефакта
    inputs:
      use_last_successful_ci:
        description: 'Use artifacts from last successful CI run'
        required: false
        default: true
        type: boolean

  # Автоматический запуск после завершения CI
  workflow_run:
    workflows: ['CI']
    types: [completed]
    branches: ['main']

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  VITE_API_KEY_FIREBASE: ${{secrets.VITE_API_KEY_FIREBASE}}

jobs:
  deploy:
    # Проверяет, что для запущенного вручную workflow выбрано использование артефакта
    # Проверяет, что триггеривший этот workflow запуск другого workflow завершился успешно
    if:
      (github.event_name == 'workflow_dispatch' && inputs.use_last_successful_ci) || (github.event_name ==
      'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'CI')

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Шаг для загрузки артефактов из последнего успешного CI при ручном запуске
      - name: Download artifacts from last successful CI (if manual trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: CI.yml
          name: ci-artifacts
          path: ./dist
          branch: main

        # Пропускаем если используем артефакты
      - name: Set up Node
        if: github.event_name != 'workflow_dispatch'
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        if: github.event_name != 'workflow_dispatch'
        run: npm ci

      - name: Build
        if: github.event_name != 'workflow_dispatch'
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
